mutation ($input: EmployeeCreateInput!) {
  createEmployee(input: $input) {
    id
	password
    name
    phoneNumber
    address
    birthdate
    startingDate
    isActive
    position{
      id
    }
  }
}
