mutation($input: EmployeeCreateInput!) {
    createEmployee(input: $input) {
        id
        password
        name
        identityCard
        phoneNumber
        address
        birthdate
        startingDate
        isActive
        position {
            id
        }
    }
}
