mutation($input: ServicesDetailUpdateInput!) {
    updateServicesDetail(input: $input) {
        id
        time
        number
        total
        booking {
            id
        }
        service {
            id
            unitRate
        }
    }
}
