mutation($input: ServicesDetailCreateInput!) {
    createServicesDetail(input: $input) {
        id
        time
        number
        booking {
            id
        }
        service {
            id
        }
    }
}
