mutation($input: VolatilityPriceUpdateInput!) {
    updateVolatilityPrice(input: $input) {
        id
        dayPrice
        nightPrice
        weekPrice
        monthPrice
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        effectiveEndDate
        effectiveOnMonday
        effectiveOnTuesday
        effectiveOnWednesday
        effectiveOnThursday
        effectiveOnFriday
        effectiveOnSaturday
        effectiveOnSunday
        createDate
        employee {
            id
        }
        roomKind {
            id
        }
    }
}
