{
    volatilityPrices {
        id
        dayPrice
        nightPrice
        weekPrice
        monthPrice
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        effectiveEndDate
        effectiveOnMonday
        effectiveOnTuesday
        effectiveOnWednesday
        effectiveOnThursday
        effectiveOnFriday
        effectiveOnSaturday
        effectiveOnSunday
        createDate
        roomKind {
            id
            name
            amountOfPeople
            numberOfBeds
        }
    }
}
