{
  houseKeepings{
    id
    type
    employee{
      id
      name
      birthdate
      address
      phoneNumber
    }
    booking{
      id
      checkInTime
      checkOutTime
      createTime
      status
    }
  }
}