mutation($input: PriceVolatilityCreateInput!) {
    createPriceVolatility(input: $input) {
        id
        dayPrice
        nightPrice
        effectiveStartDate
        effectiveEndDate
        effectiveOnMonday
        effectiveOnTuesday
        effectiveOnWednesday
        effectiveOnThursday
        effectiveOnFriday
        effectiveOnSaturday
        effectiveOnSunday
        createDate
        roomKind {
            id
        }
    }
}
