query($id: ID!) {
    priceVolatility(id: $id) {
        id
        dayPrice
        nightPrice
        effectiveStartDate
        effectiveEndDate
        effectiveOnMonday
        effectiveOnTuesday
        effectiveOnWednesday
        effectiveOnThursday
        effectiveOnFriday
        effectiveOnSaturday
        effectiveOnSunday
        createDate
        roomKind {
            id
            name
            amountOfPeople
            numberOfBeds
        }
    }
}
