query($id:ID!){
  receipt(id:$id){
    id
   	time
    money
    bankAccountNumber
    typeOfPayment
    employee{
      id
      name
      birthdate
      startingDate
      address
    }
    bill{
      id
      time
    }
  }
}