mutation($input: BillUpdateInput!) {
    updateBill(input: $input) {
        id
        time
        patron {
            identification
        }
        bookings {
            id
        }
        totalPrice
        totalReceipts
        discount
    }
}
