mutation($identification: String!, $patronUpdateInput: PatronUpdateInput!){
  updatePatron(identification: $identification, patronUpdateInput: $patronUpdateInput){
    id
    identification
    name
    birthdate
    email
    gender
    residence
    domicile
    phoneNumber
    nationality
    company
    note
    patronKind{
      id
    }
  }
}