mutation($input: PatronUpdateInput!){
  updatePatron(input: $input){
    id
    identification
    name
    birthdate
    email
    gender
    residence
    domicile
    phoneNumbers
    nationality
    company
    note
    patronKind{
      id
    }
  }
}