{
  patrons{
    identification
    name
    birthdate
    email
    gender
    residence
    domicile
    phoneNumber
    nationality
    company
    note
    patronKind{
      id
      name
      description
    }
  }
}