mutation($input: ReceiptCreateInput!) {
    createReceipt(input: $input) {
        id
        money
        time
        bankAccountNumber
        bill {
            id
        }
        employee {
            id
        }
    }
}
