{
  servicesDetails{
    id
    time
    number
    booking{
      id
      createTime
      checkInTime
      checkOutTime
      status
    }
    service{
      id
      name
      unit
      unitRate
    }
  }
}