query($id:ID!){
  servicesDetail(id:$id){
    id
    time
    booking{
      id
      createTime
      checkInTime
      checkOutTime
      status
    }
    number
    service{
      id
      name
      unit
      unitRate
      isActive
    }
  }
}