mutation($booking: BookingCreateInput!) {
    checkBookingPrice(booking: $booking) {
        id
        bookCheckInTime
        bookCheckOutTime
        realCheckInTime
        realCheckOutTime
        baseNightCheckInTime
        baseDayCheckInTime
        baseDayCheckOutTime
        total
        totalPrice
        earlyCheckInFee
        lateCheckOutFee
        price {
            id
            effectiveStartDate
            earlyCheckInFee
            lateCheckOutFee
            hourPrice
            nightPrice
            dayPrice
            weekPrice
            monthPrice
            roomKind {
                id
                name
            }
        }
        priceItems {
            value
            kind
            timeSpan
        }
    }
}
