mutation ($input: VolatilityRateUpdateInput!) {
  updateVolatilityRate(input: $input) {
    id
    dayRate
    nightRate
    weekRate
    monthRate
    lateCheckOutFee
    earlyCheckInFee
    effectiveStartDate
    effectiveEndDate
    effectiveOnMonday
    effectiveOnTuesday
    effectiveOnWednesday
    effectiveOnThursday
    effectiveOnFriday
    effectiveOnSaturday
    effectiveOnSunday
    createDate
    employee {
      id
    }
    roomKind {
      id
    }
  }
}
