{
    volatilityRates {
        id
        dayRate
        nightRate
        weekRate
        monthRate
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        effectiveEndDate
        effectiveOnMonday
        effectiveOnTuesday
        effectiveOnWednesday
        effectiveOnThursday
        effectiveOnFriday
        effectiveOnSaturday
        effectiveOnSunday
        createDate
        roomKind {
            id
            name
            amountOfPeople
            numberOfBeds
            priceByDate
        }
    }
}
