mutation($input: RateUpdateInput!) {
    updateRate(input: $input) {
        id
        dayRate
        nightRate
        weekRate
        monthRate
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        createDate
        employee {
            id
        }
        roomKind {
            id
        }
    }
}
