{
    rates {
        id
        dayRate
        nightRate
        weekRate
        monthRate
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        createDate
        roomKind {
            id
            name
            amountOfPeople
            numberOfBeds
            priceByDate
        }
    }
}
