mutation($input: PriceUpdateInput!) {
    updatePrice(input: $input) {
        id
        dayPrice
        nightPrice
        weekPrice
        monthPrice
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        createDate
        employee {
            id
        }
        roomKind {
            id
        }
    }
}
