{
    prices {
        id
        dayPrice
        nightPrice
        weekPrice
        monthPrice
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        createDate
        employee {
            id
        }
        roomKind {
            id
        }
    }
}
