query($id: ID!) {
    price(id: $id) {
        id
        dayPrice
        nightPrice
        weekPrice
        monthPrice
        lateCheckOutFee
        earlyCheckInFee
        effectiveStartDate
        createDate
        roomKind {
            id
            name
            amountOfPeople
            numberOfBeds
        }
    }
}
