mutation ($input: BookingCreateInput!) {
  createBooking(input: $input) {
    id
		createTime
    checkOutTime
    createTime
    status
    employee{
      id
    }
    bill{
      id
    }
    room{
      id
    }
  }
}