mutation($input:BookingCreateInput!){
  createBooking(input:$input){
    id
    checkInTime
    checkOutTime
    createTime
    status
    room{
      id
      name
		}
    employee{
      id
      name
    }
    bill{
      id
      time
    }
  }
}