mutation($input:RoomCreateInput!){
  createRoom(input:$input){
   id
    name
    roomKind{
      id
      name
      numberOfBeds
      priceByDate
      amountOfPeople
    }
    floor{
      id
      name
    }
  }
}