mutation($input:PositionCreateInput!){
  createPosition(input:$input){
    id
    name
    permissionReferRevenues
    permissionManageEmployees
    permissionGetRooms
    permissionManagePatrons
    permissionManagePatronKinds
    permissionHandleBills
    permissionManageHiringRooms
    permissionGetHouseKeepings
    permissionCreatePatronKind
    permissionCreateBill
    permissionCreateBooking
    permissionCreateOrUpdateEmployee
    permissionCleaning
    permissionCreateOrUpdatePatron
    permissionCreatePosition
    permissionCreateOrUpdateRate
    permissionCreateReceipt
    permissionUpdateGroundPlan
    permissionCreateOrUpdateRoomKind
    permissionCreateOrUpdateService
    permissionCreateServicesDetail
    permissionCreateOrUpdateVolatilityRate
  }
}