mutation($input:PositionCreateInput!){
  createPosition(input:$input){
    id
    name
    permissionCreatePatronKind
    permissionCreateBill
    permissionCreateBooking
    permissionCreateOrUpdateEmployee
    permissionCreateOrUpdateFloor
    permissionCreateHouseKeeping
    permissionCreateOrUpdatePatron
    permissionCreatePosition
    permissionCreateRate
    permissionCreateReceipt
    permissionCreateOrUpdateRoom
    permissionCreateOrUpdateRoomKind
    permissionCreateOrUpdateService
    permissionCreateServicesDetail
    permissionCreateVolatilityRate
  }
}