mutation($input:PositionCreateInput!){
  createPosition(input:$input){
    id
    name
    permissionCreatePatronKind
    permissionCreateBill
    permissionCreateBooking
    permissionCreateOrUpdateEmployee
    permissionCreateHouseKeeping
    permissionCreateOrUpdatePatron
    permissionCreatePosition
    permissionCreateOrUpdateRate
    permissionCreateReceipt
    permissionUpdateGroundPlan
    permissionCreateOrUpdateRoomKind
    permissionCreateOrUpdateService
    permissionCreateServicesDetail
    permissionCreateVolatilityRate
  }
}