mutation($input: PositionUpdateInput!) {
    updatePosition(input: $input) {
        id
        name
        isActive
        permissionCleaning
        permissionGetAccountingVoucher
        permissionGetHouseKeeping
        permissionGetMap
        permissionGetPatron
        permissionGetPosition
        permissionGetRate
        permissionGetService
        permissionManageEmployee
        permissionManageHiringRoom
        permissionManagePatron
        permissionManagePatronKind
        permissionManagePosition
        permissionManageRate
        permissionManageRoomKind
        permissionManageService
        permissionManageMap
    }
}
