{
  positions{
    id
    name
    permissionGetRooms
    permissionManagePatrons
    permissionHandleBills
    permissionManageHiringRooms
    permissionGetHouseKeepings
    permissionCreatePatronKind
    permissionCreateBill
    permissionCreateBooking
    permissionCreateOrUpdateEmployee
    permissionAssignHouseKeeping
    permissionCreateOrUpdatePatron
    permissionCreatePosition
    permissionCreateOrUpdateRate
    permissionCreateReceipt
    permissionUpdateGroundPlan
    permissionCreateOrUpdateRoomKind
    permissionCreateOrUpdateService
    permissionCreateServicesDetail
    permissionCreateOrUpdateVolatilityRate
  }
}