query($id: ID!) {
    position(id: $id) {
        id
        name
        permissionReferRevenues
        permissionReferDebt
        permissionChangePersonalPassword
        permissionManagePosition
        permissionManageEmployees
        permissionGetRooms
        permissionManagePatron
        permissionManagePatronKind
        permissionManageHiringRoom
        permissionGetHouseKeeping
        permissionCreatePatronKind
        permissionCreateBill
        permissionCreateBooking
        permissionCreateOrUpdateEmployee
        permissionCleaning
        permissionCreateOrUpdatePatron
        permissionCreatePosition
        permissionManageRate
        permissionCreateReceipt
        permissionUpdateGroundPlan
        permissionManageRoomKind
        permissionManageService
        permissionCreateServicesDetail
    }
}
