query($id: ID!) {
    position(id: $id) {
        id
        name
        permissionUpdateGroundPlan
        permissionGetMap
        permissionManageRoomKind
        permissionManageRate
        permissionGetRate
        permissionGetHouseKeeping
        permissionCleaning
        permissionManageHiringRoom
        permissionManagePatron
        permissionGetPatron
        permissionManagePatronKind
        permissionGetPatronKind
        permissionManagePosition
        permissionGetPosition
        permissionManageEmployee
        permissionManageService
        permissionGetService
        permissionGetAccountingVoucher
    }
}
