{
  positions {
    id
    name
    permissionUpdateGroundPlan
    permissionGetGroundPlan
    permissionManageRoomKind
    permissionManageRate
    permissionGetHouseKeeping
    permissionCleaning
    permissionManageHiringRoom
    permissionManagePatron
    permissionGetPatron
    permissionManagePatronKind
    permissionGetPatronKind
    permissionManagePosition
    permissionGetPosition
    permissionManageEmployee
    permissionManageAccount
    permissionReferDebt
    permissionReferRevenues
    permissionCreateReceipt
    permissionManageService
  }
}
