{
    positions {
        id
        name
        permissionManageMap
        permissionGetMap
        permissionManageRoomKind
        permissionManageRate
        permissionGetRate
        permissionGetHouseKeeping
        permissionCleaning
        permissionManageHiringRoom
        permissionManagePatron
        permissionGetPatron
        permissionManagePatronKind
        permissionManagePosition
        permissionGetPosition
        permissionManageEmployee
        permissionManageService
        permissionGetService
        permissionGetAccountingVoucher
    }
}
