schema {
  query: AppQuery
  mutation: AppMutation
}

type AppMutation {
  # Tạo và trả về một tầng mới
  floor(name: String!, id: Int!): Floor
}

type AppQuery {
  # Trả về thông tin một tầng
  floor(id: ID = null): Floor

  # Trả về một danh sách các tầng
  floors: [Floor]
}

# The `Date` scalar type represents a year, month and day in accordance with the
# [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
scalar Date

# The `DateTime` scalar type represents a date and time. `DateTime` expects
# timestamps to be formatted in accordance with the
# [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
scalar DateTime

# The `DateTimeOffset` scalar type represents a date, time and offset from UTC.
# `DateTimeOffset` expects timestamps to be formatted in accordance with the
# [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
scalar DateTimeOffset

scalar Decimal

# Một tầng trong khách sạn
type Floor {
  # Id của tầng
  id: Int!

  # Tên tầng
  name: String!
}

# The `Milliseconds` scalar type represents a period of time represented as the total number of milliseconds.
scalar Milliseconds

# The `Seconds` scalar type represents a period of time represented as the total number of seconds.
scalar Seconds

