mutation($input: PositionCreateInput!) {
    createPosition(input: $input) {
        id
        name
        permissionCleaning
        permissionGetAccountingVoucher
        permissionGetHouseKeeping
        permissionGetMap
        permissionGetPatron
        permissionGetRate
        permissionGetService
        permissionManageEmployee
        permissionManageRentingRoom
        permissionManageMap
        permissionManagePatron
        permissionManagePatronKind
        permissionManagePosition
        permissionManageRate
        permissionManageService
    }
}
