mutation($input: PositionUpdateInput!) {
    updatePosition(input: $input) {
        id
        name
        isActive
        permissionCleaning
        permissionGetAccountingVoucher
        permissionGetMap
        permissionGetPatron
        permissionGetRate
        permissionGetService
        permissionManageEmployee
        permissionManageRentingRoom
        permissionManageMap
        permissionManagePatron
        permissionManagePatronKind
        permissionManagePosition
        permissionManageRate
        permissionManageService
    }
}
