mutation($input: PositionCreateInput!) {
    createPosition(input: $input) {
        id
        name
        permissionCleaning
        permissionGetAccountingVoucher
        permissionGetMap
        permissionGetPatron
        permissionGetPrice
        permissionGetService
        permissionManageEmployee
        permissionManageRentingRoom
        permissionManageMap
        permissionManagePatron
        permissionManagePatronKind
        permissionManagePosition
        permissionManagePrice
        permissionManageService
    }
}
