query($id: ID!) {
    position(id: $id) {
        id
        name
        permissionCleaning
        permissionGetAccountingVoucher
        permissionGetMap
        permissionGetPatron
        permissionGetRate
        permissionGetService
        permissionManageEmployee
        permissionManageRentingRoom
        permissionManageMap
        permissionManagePatron
        permissionManagePatronKind
        permissionManagePosition
        permissionManageRate
        permissionManageService
    }
}
