mutation ($bookings: [BookingCreateInput!]!, $bill: BillCreateInput!) {
  createBill(bookings: $bookings, bill: $bill) {
    id
    time
    patron {
      id
    }
    employee {
      id
    }
    bookings {
      id
    }
  }
}
