mutation($bookings: [BookingCreateInput!]!, $bill: BillCreateInput!) {
    bookAndCheckIn(bookings: $bookings, bill: $bill) {
        id
        time
        patron {
            id
        }
        employee {
            id
        }
        bookings {
            id
        }
    }
}
